### ISSUE TITLE
model release

### ISSUE THREAD

**Issue by Shandelier** [cvlab-stonybrook/HAT#1]
hi

Still reading the paper, but the idea of implementing "foveated retina" is awesome! Congratulations on obtaining SotA :)

Are you planning to release the model weights?

best wishes

**Comment by ouyangzhibo** [comment]
> hi
> 
> Still reading the paper, but the idea of implementing "foveated retina" is awesome! Congratulations on obtaining SotA :)
> 
> Are you planning to release the model weights?
> 
> best wishes

Sorry for the late reply. Yes, we'll release the model weights in a bit. Stay tuned.

**Comment by ouyangzhibo** [comment]
Models are released, feel free to try out the demo.

**Comment by Shandelier** [comment]
thanks, will check it out!
