### ISSUE TITLE
the structure of dataset root

### ISSUE THREAD

**Issue by foxquan** [cvlab-stonybrook/HAT#2]
hello：
I want to train the model to predict free-viewing scanpaths. Can you tell me the structure of the <dataset root>.

**Comment by ouyangzhibo** [comment]
Sorry for the late reply. For the data preparation, please follow https://github.com/cvlab-stonybrook/Scanpath_Prediction.

**Comment by Fy-Zqy** [comment]
hello:
I want to train a freeviewing model. Do I need bbox_onnos.npy in this root directory

**Comment by RuoyuX-2018** [comment]
Please find all required data from this link: 
https://drive.google.com/drive/folders/1GOmWlDpG6Lh7iPlt9Hi9GWZ4BAfwhmHR?usp=drive_link

**Comment by Fy-Zqy** [comment]
hello:
If I use my own image data, how should I prepare a dataset for training a freeviewing model, what image processing do I need to do, and how can I process these images to meet the requirements of the dataset

**Comment by RuoyuX-2018** [comment]
Thank you for pointing it out! We have updated the readme.md for training HAT on a custom dataset.

**Comment by Fy-Zqy** [comment]
Thank you for patiently explaining!
